### ISSUE TITLE
Move the approval code to the App_Packages directory

### ISSUE THREAD

**Issue by SimonCropp** [JakeGinnivan/ApiApprover#10]
As per point 2 here http://nikcodes.com/2013/10/23/packaging-source-code-with-nuget/

should also adopt the `{package-id}.{package-version}` since this helps with updates

this also allows people to exclude your nuget source package from stylecop and resharper inspections

Want a PR?

**Comment by JakeGinnivan** [comment]
That would be great :)

Sent from my Windows Phone
________________________________

**Comment by JakeGinnivan** [comment]
Released. Thanks :)
