### ISSUE TITLE
Transitive references broken on project.json - missing dependency versions in nuspec

### ISSUE THREAD

**Issue by onovotny** [JakeGinnivan/ApiApprover#14]
The NuSpec/NuGet package for API Approver is missing the dependency versions:
http://www.nuget.org/packages/ApiApprover/

This causes project.json-based projects to fail to properly resolve the dependencies. At the very least, minimum versions should be specified.

**Comment by danielmarbach** [comment]
Thanks @onovotny. Sorry that nobody actually took action on this. We recently upgraded to the new csproj system and support .NET Standard 2.0. Currently, we specified a minimum version for the package.
