### ISSUE TITLE
Binary package

### ISSUE THREAD

**Issue by mexx** [JakeGinnivan/ApiApprover#15]
What were the reasons that the binary package was dropped?
With the current version 3.0.1 there is no way to have the tests in some other .NET language as C#, or is there?

**Comment by JakeGinnivan** [comment]
That is a good point. I think I will switch to a binary package

I also think I will just change this library to generate a string representation of your library? That way you can use whatever approval library you want

**Comment by JakeGinnivan** [comment]
I have pushed https://www.nuget.org/packages/PublicApiGenerator/4.0.0

You can now just use that, then use approvaltests or shouldly directly to approve the output. This should simplify things :)

**Comment by mexx** [comment]
Cool, thank you.
