### ISSUE TITLE
Handle different access modifiers for property getters and setters

### ISSUE THREAD

**Issue by dee-see** [JakeGinnivan/ApiApprover#16]
I've seen the `// TODO: CodeDOM has no support for different access modifiers for getters and setters` comment in PublicApiGenerator.cs.

What would you think of using `CodeSnippetTypeMember` instead of `CodeMemberProperty` and generating the text for the property manually? It would allow us to work around Code DOM's limitation.

If you agree with the feature I don't mind working on it and sending a pull request.

**Comment by dee-see** [comment]
I've looked a bit into it and `CodeSnippetTypeMember` is not indented properly by the `CSharpCodeProvider`. The idea could work but the result wouldn't look as clean...

**Comment by danielmarbach** [comment]
Thanks @dee-see for your input and your efforts in investigating this. Based on your comment I'm closing this issue.
