### ISSUE TITLE
Allow an attributes whitelist to be passed to the Generator on invocation

### ISSUE THREAD

**Issue by dee-see** [JakeGinnivan/ApiApprover#17]
There are some attributes in my code that can change without inducing any breaking change to the API.

It would be nice to be able to give a list of attributes that would be combined with the `SkipAttributeNames` collection when the `ShouldIncludeAttribute` evaluates whether an attribute should be included or not.

If you agree with the feature I don't mind working on it and sending a pull request.

**Comment by JakeGinnivan** [comment]
There are many changes which are non-breaking. Adding a method, or a new class for instance.

The idea of this is simply generate the public API, review and approve the changes with approval tests or shouldly's ShouldMatchApproved().

That said, if this is to reduce noise in general then sure I see no issues with this feature. I would probably use it for jetbrains annotations.

**Comment by dee-see** [comment]
Yeah I misused the term breaking change. I meant that some attributes are not API changes at all, they are merely metadata.

I'm going to work on that and submit a pull request soon. Thanks!

**Comment by danielmarbach** [comment]
Replaced by #45
