### ISSUE TITLE
ApiApprover does not list public members for Microsoft projects

### ISSUE THREAD

**Issue by SeanFeldman** [JakeGinnivan/ApiApprover#32]
Related to the fact that the check in place excludes any member that is of type defined in either `System` or `Microsoft` namespace. Aside from changing [`ApiGenerator` code](https://github.com/JakeGinnivan/ApiApprover/blob/3df8f29e89761e5071a596bb752ead4d6de81e5f/src/PublicApiGenerator/ApiGenerator.cs#L117) to white-mark a specific sub-namespace under `Microsoft.<sub-namespace>` namespace and then do it again whenever a package is updated, perhaps there should be a better way to exclude current project's namespace? Thanks.

**Comment by SeanFeldman** [comment]
4 months and no response. I'll submit a PR to address this issue and would appreciate if maintainers could yay/nay the following approach.

1. Introduce an optional predicate for [`ApiGenerator.GeneratePublicApi()`](https://github.com/JakeGinnivan/ApiApprover/blob/3df8f29e89761e5071a596bb752ead4d6de81e5f/src/PublicApiGenerator/ApiGenerator.cs#L22) to white-list namespaces that would normally get filtered out.
1. Use the predicate in the [`IsDotNetTypeMember()`](https://github.com/JakeGinnivan/ApiApprover/blob/3df8f29e89761e5071a596bb752ead4d6de81e5f/src/PublicApiGenerator/ApiGenerator.cs#L117) method.

**Comment by danielmarbach** [comment]
how about we turn it around and have the standard exclusions available and exclusions can be passed into the API. So essentially to overloads 

public static string GeneratePublicApi(Assembly assemby, Type[] includeTypes = null, bool shouldIncludeAssemblyAttributes = true, string[] excludeNamespaces)

if you don't specify the exclude it will use the standard one

**Comment by SeanFeldman** [comment]
👍  Would it mean that the signature be `public static string GeneratePublicApi(Assembly assemby, Type[] includeTypes = null, bool shouldIncludeAssemblyAttributes = true, string[] excludeNamespaces = null)` with `excludeNamespaces` defaulted to null?
