### ISSUE TITLE
Which constructors to hide?

### ISSUE THREAD

**Issue by Litee** [JakeGinnivan/ApiApprover#5]
According to current unit tests default protected constructors should be shown for standard classed and hidden for abstract classes. Any logic behind that?

**Comment by JakeGinnivan** [comment]
That sounds like a bug. Protected abstract ctors are part of the public API

**Comment by JakeGinnivan** [comment]
Fixed by 19cae50cb05542c5e2548b06c6a3850b334e7e2e
