### ISSUE TITLE
Feature request: .NET Core Global Tool for PublicApiGenerator

### ISSUE THREAD

**Issue by jskeet** [JakeGinnivan/ApiApprover#55]
It would be *fabulous* to be able to run something like:

```text
dotnet printapi --package NodaTime --version 1.3.0 --framework netcoreapp1.0
```

or

```text
dotnet printapi --project src/NodaTime --framework netcoreapp1.0
```

I'm envisaging the framework being "one to use when restoring packages" - not necessarily one that is directly supported by the project.

The rough behaviour would be:

- Create an empty working area
- Create a project file with the appropriate dependency to the package/project, and target framework
- Run `dotnet publish`
- Run PublicApiGenerator on the relevant assembly in the publish directory and print the result to the console

(For packages that have multiple assemblies or don't follow the package name == assembly name convention, we might want a `--assembly` flag too.)

That's basically what I've done in [this commit](https://github.com/googleapis/google-cloud-dotnet/commit/b5c7d0f1b317d37fb80ff30b64c102b14bdd80e2), but not nearly as nicely as having a global tool. (It also makes some assumptions that are specific to that repo.)

**Comment by danielmarbach** [comment]
@jskeet I tried to give it a go

https://github.com/JakeGinnivan/ApiApprover/pull/61

I still need to figure out the path for the csproj and I'm wondering if that is really required over whether it would be enough if one could point the tool to an assembly on disk and then it would just use that one. I'm thinking linking to an actual csproj might assume that the tool has all the context to build that csproj which might not be the case

Thoughts

**Comment by jskeet** [comment]
Pointing to an assembly on disk doesn't handle the dependencies nicely. The benefit of using the csproj file (and I'm absolutely fine for the `--project` argument to require the full path to the csproj file, btw) is that `dotnet publish` works and takes all the dependencies into account.
It definitely requires having all the context required to build the project - but in the use cases I've been considering ("I want to know the API for my project's current state vs the state of a past build that's on nuget") that's not a problem. I'm not sure how often you'd have a use case of wanting to specify a project file but not be able to build that project locally.

**Comment by danielmarbach** [comment]
As of now the approach in the PR uses a temp directory to create a CSPROJ. But I haven't managed to add a project reference to a full path into that temporary project to build. It trips up dotnet build. Any pointers would be appreciated 

Currently, I'm also doing a bit of trickery to avoid loading the assembly into the tool appdomain. The generated project has all the logic to generate the API from the args passed to the project. With that I can dotnet run that generated output and then just delete the temporary files. If the assemblies get loaded into the app domain I can't delete the temporary files anymore.

**Comment by jskeet** [comment]
Hmm... I didn't have any problem including a reference to a csproj file within the temporary project. What happened when you tried?

I see why you're using dotnet run in terms of temporary files. That does mean the target framework has to be an "app" framework rather than (say) "netstandard2.1" or similar.

**Comment by danielmarbach** [comment]
Got it to work on the latest commit on that PR

Yes the target framework has to be an APP framework. I don't see this as a problem though because the APP framework determines which API shape you are going to get and thus the generated API will still reflect the reality. Do you see any issues here?

**Comment by jskeet** [comment]
The downside is that if I'm writing a library targeting (say) netstandard2.0, and I want to consume the API of another library, it's harder to know what will be available to me from the perspective of netstandard2.0, not netcoreapp2.0. It's only a minor disadvantage though - and we could always look at it again if it turns out to be a practical problem in the real world. But yay that the csproj is working :)

**Comment by danielmarbach** [comment]
I released beta3 of the global tool and documented the switches and some usage scenarios available at

https://github.com/JakeGinnivan/ApiApprover/#publicapi-generator-global-tool

```
dotnet tool install -g PublicApiGenerator.Tool --version 9.0.0-beta3
```

see

In order to be able to try out the beta version you always need to specify the `---generator-version` switch and specify the current beta like

```
--generator-version 9.0.0-beta3
```

**Comment by danielmarbach** [comment]
Released the tool as final

https://github.com/JakeGinnivan/ApiApprover#publicapi-generator-global-tool

Fingers crossed it works ;) I didn't get much feedback

**Comment by jskeet** [comment]
Apologies for not getting back to you before - thank you so much for doing this :)
