### ISSUE TITLE
Ordinal ordering of classes, interfaces, members and fields

### ISSUE THREAD

**Issue by danielmarbach** [JakeGinnivan/ApiApprover#56]
Currently, default string ordering is used which can lead to inconsistent ordering depending on the environment in which the API diff is generated. Ideally ordering of classes, interfaces, members and fields should be done using the StringComparison.Ordinal ordering rules.

**Comment by jonorossi** [comment]
@danielmarbach is there a reason you chose `Ordinal` rather than `OrdinalIgnoreCase`?

I'm updating Castle to use the newest version and found heaps of types/members move around because of this change. Any chance you'll change to ignore case, or should I just push forward with everything moving around?

**Comment by danielmarbach** [comment]
The previous version used culture aware ordering that did not ignore casing as far as I remember. Used Ordinal to sort the type ordering issue and make it consistent over windows and linux environments. I have no crystal ball but currently the plan is to leave as is unless strong reasons are presented

**Comment by jonorossi** [comment]
> The previous version used culture aware ordering that did not ignore casing as far as I remember.

At least from our usage with Castle (using English cultures) it has sorted, for example:
- `GetArguments` then `GetArgumentValue`
- `CreateInterfaceProxyTypeWithoutTarget` then `CreateInterfaceProxyTypeWithTarget`
- `InvalidMixinConfigurationException` then `IProxyBuilder`

These changes flip them around, so uppercase letters come first. Everything is still there, was just an unexpected change, however good to know at least a stable sort has been chosen.

> I have no crystal ball but currently the plan is to leave as is unless strong reasons are presented

Thanks, wanted to know it was a conscious decision and isn't likely to change.

**Comment by danielmarbach** [comment]
Whenever the API output changes I bump the major.

**Comment by jnm2** [comment]
I also prefer OrdinalIgnoreCase. It makes things hard to find alphabetically when scanning when `VSTS` is sorted before `VisualStudio` because `S` < `i`, or when ShouldlyConfiguration is sorted under ShouldThrowTaskExtensions because `T` < `l`.

 Ordinal puts all lowercase letters after all uppercase letters and that doesn't make sense to me.

**Comment by jnm2** [comment]
10 is currently in beta. Now would be the chance to fix...

**Comment by sungam3r** [comment]
I am against this, because order can become non-deterministic:
VisualStudioHelper
VisualSTUDIOhelper
visualstudiohelper

> It makes things hard to find alphabetically when scanning 

Is this a real task that often arises? You can always find by search.

**Comment by sungam3r** [comment]
> Ordinal puts all lowercase letters after all uppercase letters and that doesn't make sense to me.

It is deterministic so it makes sense to me.

**Comment by jnm2** [comment]
I don't think it's non-deterministic. Even if case is not already used as a tiebreaker, it's easy to add.

> Is this a real task that often arises? You can always find by search.

No, but I do read through them. It's just annoying to look at and would be a significant factor for me when considering which tool to use. I like my APIs to look nice.

Also, I'm updating Shouldly from v8 and things are jumping around. If this was changed to a deterministic ordinal ignore-case sort in v10, nothing would jump.

**Comment by jnm2** [comment]
You're right that OrdinalIgnoreCase is non-deterministic, but you could replace `StringComparer.OrdinalIgnoreCase` with `DeterministicOrdinalIgnoreCaseComparer.Instance` and that problem would be solved:

```cs
public sealed class DeterministicOrdinalIgnoreCaseComparer : IComparer<string>
{
    public static DeterministicOrdinalIgnoreCaseComparer Instance { get; }

    private DeterministicOrdinalIgnoreCaseComparer() { }

    public int Compare(string x, string y)
    {
        var comparison = string.Compare(x, y, StringComparison.OrdinalIgnoreCase);
        if (comparison == 0) comparison = string.Compare(x, y, StringComparison.Ordinal);
        return comparison;
    }
}
```

**Comment by sungam3r** [comment]
That's better

**Comment by danielmarbach** [comment]
I don't want to step on anyone's toes because ultimately the arguments presented so far here are subjective. The most important part is the determinstic sorting across across OSS and culture. Thats what we achieved and that is good enough. Some peopld might definitely want a more intuitive sorting that follows a certain way of of thinking while others just want deterministic output and do not care about the sorting as long as it is comparable with differs. Given that discussions around topics like that can go back and forth and become heated I'm leaning towards locking this down
