### ISSUE TITLE
Multiline text in attributes differs on Windows and Linux

### ISSUE THREAD

**Issue by sungam3r** [JakeGinnivan/ApiApprover#75]
I found that when using multi-line text in attributes, our tests fail with on CI, although locally everything is fine. The reason is line endings although it seems that ApiApprover already has built-in tools to bypass it. I use `ObsoleteAttribute` with detailed description which takes several lines. So I have `\r\n` literal in the middle of the line in approved file on Windows machine but on CI build server I get an error with `\n` literal. I use Shouldly - `ShouldMatchApproved` method.

I went through the ApiApprover code as a debugger (normalizing strings, etc.), but I didn’t figure out what should be done in this case.

**Comment by sungam3r** [comment]
![image](https://user-images.githubusercontent.com/21261007/62862524-bb3c6500-bd0e-11e9-825c-bf3330ac7a4a.png)
@danielmarbach What does it mean?

Because of that normalization [this replace](https://github.com/shouldly/shouldly/blob/master/src/Shouldly/Internals/StringHelpers.cs#L178) in Shouldly does not work:
![image](https://user-images.githubusercontent.com/21261007/62862583-e8891300-bd0e-11e9-81d3-480096ad7291.png)

Before normalization:
![image](https://user-images.githubusercontent.com/21261007/62862690-46b5f600-bd0f-11e9-9ed0-c746dd4b6487.png)

After normalization:
![image](https://user-images.githubusercontent.com/21261007/62862720-5e8d7a00-bd0f-11e9-8938-e49bfdb1bb5e.png)

**Comment by danielmarbach** [comment]
I have no idea honestly why this code is there. Paging @JakeGinnivan maybe he recalls. 

That being said can't shouldly ignore those cases?

**Comment by sungam3r** [comment]
Shouldly **can** ignore line endings, but the problem is that `\\r\\n` **is no longer** a line ending.

**Comment by danielmarbach** [comment]
So the code does this

```
        static string NormaliseLineEndings(string value)
        {
            return Regex.Replace(value, @"\r\n|\n\r|\r|\n", Environment.NewLine);
        }
```

which replaces it with the platform-specific variant NewLine. So that means you'd have to Replace Newline with `\r\n` before you pass it to shoudly and then you'd be safe correct?

**Comment by sungam3r** [comment]
It seems to me that no. `NormaliseLineEndings` in my case does not replace anything because I have `\\r\\n` in value. This is just **another** character sequence that Shouldly leaves **unchanged**. The key question is not what Shouldly does, but what ApiApprover does - that obscure "normalization".

Why not just leave the attribute value as it is - with all the original line feeds without any "normalization"? What is meant by simplicity of comparison in a comment? It turned out the opposite complication.

**Comment by danielmarbach** [comment]
@JakeGinnivan any insights from your side?

**Comment by JakeGinnivan** [comment]
Honestly do not remember either. Sorry :(

**Comment by danielmarbach** [comment]
Ok I guess then I will play around with the code a bit when I have time to better understand the implications of those normalizations and how my crazyness comes out of the code compiler by default

**Comment by danielmarbach** [comment]
Honestly though I'm a bit on the fence how much effort is worth because I know quite a few teams that run this code on multiple platform without shouldly but don't have that problem

**Comment by sungam3r** [comment]
Probably they are not inclined to write lengthy descriptions in attributes.

**Comment by danielmarbach** [comment]
Well at particular for example we have really lengthy attributes. Will check there as well-------- Ursprüngliche Nachricht --------Betreff: Re: [JakeGinnivan/ApiApprover] Multiline text in attributes differs on Windows and Linux (#75)Von: Ivan Maximov An: JakeGinnivan/ApiApprover Cc: Daniel Marbach ,Mention Probably they are not inclined to write lengthy descriptions in attributes.

**Comment by danielmarbach** [comment]
So I looked into this a bit. With NServiceBus we also have multi line attributes but we have no issue so far because our gitattributes normalizes line endings. As I can see graphql has

```
* text=auto
```

while we have

```
# Auto detect text files and perform CRLF normalization
* text=auto eol=crlf
```

Currently, all `\n` get turned into `\\n` and any combination of `\r\n` or `\r\\n` gets turned into `\\r\\n` and then they get normalized with `Environment.NewLine` which is under Windows `\r\n` and under nix environments it is `\n`. 

The test you sent in that fails hardcodes the expectation to be `\\r\\n` which is only true under Windows but not under Linux so therefore it fails. 

What would be your expectation of this library? What should it do for you or shouldn't it do? Would you want the ability to replace the normalization function which something that is consistent over all the platforms?

**Comment by sungam3r** [comment]
I want my approval test to work on both windows and nix. I do not want to hardcode anything. I just run api generator first time, renamed received file into approved then run test again and it passed. Then I pushed all this onto Cl and test failed. I did not hardcode anything manually.

**Comment by danielmarbach** [comment]
Well like I said you can achieve that by changing the line endings for the approval files in gitattributes or replacing the Environment.NewLine with something hardcoded for now. From the perspective of this library it might make sense to normalize towards /r/n or /n independent from the platform in the next major -------- Ursprüngliche Nachricht --------Betreff: Re: [JakeGinnivan/ApiApprover] Multiline text in attributes differs on Windows and Linux (#75)Von: Ivan Maximov An: JakeGinnivan/ApiApprover Cc: Daniel Marbach ,Mention I want my approval test to work on both windows and nix. I do not want to hardcode anything. I just run api generator first time, renamed received file into approved then run test again and it passed. Then I pushed all this onto Cl and test failed. I did not hardcode anything manually.

**Comment by bording** [comment]
I'll need to take a closer look at what is going on the code to see if something here is wrong, but in general this library shouldn't be responsible for handling line ending differences. That should be handled by source control and the approval test library that consumes the files created by this library.

**Comment by adamralph** [comment]
To ensure I understand, is this when you have:

```c#
[AnAttribute(
@"With a property
defined over
several lines?")]
```

Presumably this isn't limited to attributes? I guess you could also have a

```c#
public const string Defined =
@"Over
several
lines?";
```

If so, then I agree with @bording that this library should not do anything special with line endings.

Indeed, a change to the line endings in these values _is a breaking change_. A consumer could be checking for `/r/n`, and in the next version, you change that to `/n` and their code blows up.

A line ending character in a code base is just like any other character on the code base. It is the responsibility of the maintainers to... maintain them. "Special" treatment of line endings is what leads to problems like these.

**Comment by sungam3r** [comment]
Repeat of my comment:
Shouldly (consumer) **can** handle (ignore) different line endings, but the problem is that \\r\\n after apiapprover "normalization" **is no longer a line ending**.

**Comment by sungam3r** [comment]
> Presumably this isn't limited to attributes?

It is only used in `static CodeExpression CreateInitialiserExpression(CustomAttributeArgument attributeArgument)`, so for attribute values only. My test failed on rather long dexcription text in `ObsoleteAttribute`.

**Comment by adamralph** [comment]
I'm not sure I fully understand this scenario, but if this library is currently doing something special with line endings then that behaviour should probably be removed.

**Comment by danielmarbach** [comment]
I synced with @adamralph again to clarify a few things and we both came to the conclusion that the public api generator doing the right thing. The API generator inspects the assembly metadata and creates a sharp equivalent of the public API. If an attribute in a source file contains literal newline or carriage return line feed characters the csharp equivalent is the escaped version of these literals. 

The problem seen here is not solvable from a public api generator perspective. The graphql repository contains

```
* text=auto
```

which mingles the line endings on the way into the repository. Thus when a csharp file created on Windows with an attribute that contains `/r/n` public API generator will escape it in the csharp equivalent to `//r//n`. With the line ending mingling, the source file gets checked out on linux with LF only which then gets escaped to `//n` thus the test fails.

Like @adamralph mentioned though the Api generator doesn't apply that behavior consistently. For example right now the attribute code only deals with `/r/n` and `/n` and for example doesn't deal with `/t` or other literal characters. This should probably be fixed. As well as applying the same behavior for constant strings

**Comment by sungam3r** [comment]
`* text=auto eol=crlf` works, thanks.
