### ISSUE TITLE
System.Exception from ShouldMatchApproved

### ISSUE THREAD

**Issue by sungam3r** [JakeGinnivan/ApiApprover#77]
On this [PR](https://github.com/graphql-dotnet/graphql-dotnet/pull/1247) I have that error: https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/builds/26733618/tests

System.Exception : Source information not available, make sure you are compiling with full debug information. Frame: **RuntimeMethodHandle.InvokeMethod**

It seems to me that `TestMethodFinder` found not my method, but the framework method.

On my Windows machine, the test is successful.

**Comment by danielmarbach** [comment]
It looks like this is related to how shouldly tries to walk the stack frames to discover the entry method. Sounds like a bug for shouldly? ApiGenerator is not depending on shouldly

**Comment by sungam3r** [comment]
Oh, I wrote here out of habit.
