### ISSUE TITLE
Incorrect API generated for readonly structs

### ISSUE THREAD

**Issue by gpetrou** [JakeGinnivan/ApiApprover#78]
We have declared a struct like:
   
    public readonly struct Matrix

However, the generated API is:

    public struct Matrix

Would it be possible to add support for readonly structs?

**Comment by danielmarbach** [comment]
Did a [quick spike](https://github.com/JakeGinnivan/ApiApprover/pull/84) and hacky support for it would be possible. Because of the internal usage of code dom the `readonly` would come after `struct` but hey you can't win them all ;)
