### ISSUE TITLE
In-modifier is recognised as ref

### ISSUE THREAD

**Issue by gpetrou** [JakeGinnivan/ApiApprover#79]
We have the following constructor:

    public Matrix(in Matrix)

However, the generated API is:

    public Matrix(ref Matrix)

Would it be possible to add support for in-modifier?

**Comment by danielmarbach** [comment]
So I spiked rudimentary in modifier support in https://github.com/JakeGinnivan/ApiApprover/pull/85. Have a look. What do you think?
