### ISSUE TITLE
Attribute missing from method

### ISSUE THREAD

**Issue by gpetrou** [JakeGinnivan/ApiApprover#81]
We have the following method:

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool MyMethod(float a, float b) { return false; }

However, the attribute is missing from the generated API.
Would it be possible to add this?

**Comment by sungam3r** [comment]
Use `whitelistedNamespacePrefixes` parameter.

**Comment by danielmarbach** [comment]
What @sungam3r said. Though I'm curious why you would ever want this attribute in your API definition

**Comment by danielmarbach** [comment]
Closing this as won't fix because namespaces can be white listed as mentioned previously
